### ISSUE TITLE
Refresh UI Machine as done in Job 

### ISSUE THREAD

**Issue by Psyf** [CS2113-AY1819S1-T09-1/main#130]

**Comment by Psyf** [comment]
Using the same strategy as JobListView does not work since it resets the View to the top

**Comment by Psyf** [comment]
Maybe this: https://www.jensd.de/wordpress/?p=1650

@trufflepirate we have to make sure fixing this bug in 1.4.1 is worth it or not.

**Comment by trufflepirate** [comment]
fixed in #151
