### ISSUE TITLE
Remove Machine

### ISSUE THREAD

**Issue by Psyf** [CS2113-AY1819S1-T09-1/main#131]
I feel like this feature is essential to the product.

**Comment by teojunjie** [comment]
Ok noted. I got a couple of questions i need you to address.
1) What happens to the jobs from this machine when it is removed?
-  Does it get added to another machine through auto?
-  Manually add it to the most free machine?
2) If the machine is currently executing a job, what happens?
-  Does the machine wait till the job is completed? Or does it cancel the job and then add all unfinished jobs to another machine?

**Comment by Psyf** [comment]
Very good questions @teojunjie 

I think for all of the above questions, the user(in this case the admin) should be prompted to do something about it (with appropriate error messages) before he is allowed to remove the machine.

**Comment by Psyf** [comment]
Addressed in #134
