### ISSUE TITLE
Decide on and Redesign StorageManager 

### ISSUE THREAD

**Issue by Psyf** [CS2113-AY1819S1-T09-1/main#14]
This is necessary for using separate files for machines, admins, and jobs. 
This is an important design decision and the implementation direction will be very different depending on what we decide on as a team.

**Comment by trufflepirate** [comment]
I am of the opinion that we should go to the second way, 3 different files persistent storage. We should prioritize working on this so that the rests of the features can be tested manually during runtime.

**Comment by Psyf** [comment]
The latter option was chosen by the team. Work underway for version 1.2

**Comment by Psyf** [comment]
@teojunjie 's PR solves it
