### ISSUE TITLE
UniqeMachineListTest::addJobToMachineList() failing

### ISSUE THREAD

**Issue by Psyf** [CS2113-AY1819S1-T09-1/main#144]
@teojunjie please take a look at this ASAP
I've commented it out in my latest PR.

**Comment by teojunjie** [comment]
Yeap i removed it. Did u pull from my branch?

**Comment by teojunjie** [comment]
I will fix it soon

**Comment by trufflepirate** [comment]
It fails gradle but not when intellij runs it

**Comment by trufflepirate** [comment]
i know why this breaks

**Comment by Psyf** [comment]
Why did it break?

**Comment by trufflepirate** [comment]
the other tests were modifying the Machine that The test was adding to. So depending on the tests run before this, the Machine might or might not already have some junk Jobs inside

**Comment by teojunjie** [comment]
Has this issue been addressed?

**Comment by trufflepirate** [comment]
fixed in #151. Explain in person
