### ISSUE TITLE
Implement a set of sample data

### ISSUE THREAD

**Issue by Ftywan** [CS2113-AY1819S1-T09-1/main#156]
The default option for initializing the app is starting from a sample data file, which current containing the data for Persons. A new set of sample data need to be defined.

**Comment by Psyf** [comment]
We actually don't need to do this. 
See this: https://github.com/nusCS2113-AY1819S1/forum/issues/107
Please implement. 

@Psyf @teojunjie @trufflepirate

**Comment by Psyf** [comment]
Perhaps we should just include the .zip file on github and include instructions in the UG and the DG?
@trufflepirate

**Comment by teojunjie** [comment]
@Psyf my question is where do we upload the the data.zip file on github? Along with the release for v1.4? And then in the developer guide we just say look for the data set in the release for v1.4 and do the instructions stated in the developer guide?

**Comment by Psyf** [comment]
Sorry for the delayed response. Answer conveyed on the whatsapp channel.

**Comment by teojunjie** [comment]
.zip file has been added to pr #153
