### ISSUE TITLE
Do we need this event? 

### ISSUE THREAD

**Issue by Psyf** [CS2113-AY1819S1-T09-1/main#24]
https://github.com/CS2113-AY1819S1-T09-1/main/blob/94716c78e4f986c7ade433c18eb8417bcbf46521/src/main/java/seedu/address/model/ModelManager.java#L124-136

These two methods in `ModelManager` are changing only the `versionedAddressBook` or `in-memory` Addressbook. It will not be touching the files. Should we keep `indicateAddressBookChanged()` event, even though it's quite useless at this point?

I suggest keeping `AddressBookChangedEvent` (and upcoming similar events) only if files are handled.

**Comment by trufflepirate** [comment]
I don't think this event is required. Since the login state is unique to each session and not saved across sessions.
