### ISSUE TITLE
add : request deletion of print job

### ISSUE THREAD

**Issue by teojunjie** [CS2113-AY1819S1-T09-1/main#40]
As a student, i want to be able to request deletion of my print job so that i can cancel any printing job that has not been executed yet.

**Comment by Psyf** [comment]
Right now anyone can delete any print. Does that solve the dependency on #42 @teojunjie?

**Comment by teojunjie** [comment]
Nope it doesnt solve the dependency at the moment still working on implementing it by tianyuan . Noted

**Comment by teojunjie** [comment]
request deletion completed and integrated with ui.

**Comment by teojunjie** [comment]
will only close this issue when pr is successfully merged and tested.
