### ISSUE TITLE
Addressing Reviews for PR#30

### ISSUE THREAD

**Issue by Psyf** [CS2113-AY1819S1-T09-1/main#48]
Hi @teojunjie, 

Please address the reviews added to #30 that you merged. Please ensure that in the future you address them before someone else merges your PR. Refrain from merging your own, and that is a rule for all of us. This should keep the progress clean, and make sure nothing is missed in the hectic schedule. 

Thanks for understanding. 

Best, 
Saif

**Comment by teojunjie** [comment]
Noted! Have addressed the review accordingly
