### ISSUE TITLE
FlushMachine and CleanMachine

### ISSUE THREAD

**Issue by Psyf** [CS2113-AY1819S1-T09-1/main#55]
Flush Machine = clears all Jobs from the machine
cleanMachine = delete all FINISHED and CANCELLED Job from the machine

**Comment by teojunjie** [comment]
Ok noted. I will probably do this in line with #131  as they seem to be interlinked for this feature of removeMachine. Like maybe when i remove machine, it will flush machine and clean machine first? or something i will figure out the implementation

**Comment by Psyf** [comment]
Won't let admin removeMachine as long as there are Jobs in it. He'll have to manually flush or move jobs away.

**Comment by Psyf** [comment]
To clarify: 
- flushMachine will ask you to move jobs away, or risk losing them all. 
- removeMachine won't let you remove until you move away/flush 
- cleanMachine has no such problems since you're only cleaning out (i.e deleting) CANCELLED or FINISHED ones (to make the UI less clunky)

Hope that answers your questions.

**Comment by Psyf** [comment]
Addressed in #134
