### ISSUE TITLE
Adding another Job with same name does nothing

### ISSUE THREAD

**Issue by Psyf** [CS2113-AY1819S1-T09-1/main#62]

**Comment by Ftywan** [comment]
Request of adding a job with the same name will be declined and notified there is a job with the same name in the job list

**Comment by Psyf** [comment]
Is this implemented in a current PR?

**Comment by Ftywan** [comment]
![screen shot 2018-10-24 at 11 32 58](https://user-images.githubusercontent.com/34418860/47404616-975c6280-d780-11e8-831f-88d2125f7670.png)
Implemented. Seen in screenshot.

**Comment by Ftywan** [comment]
![screen shot 2018-10-24 at 11 34 31](https://user-images.githubusercontent.com/34418860/47404672-cb378800-d780-11e8-928c-5f5138f83fbe.png)
Still working in the condition that the configuration is not the same

**Comment by Ftywan** [comment]
Solved and updated in #63
