### ISSUE TITLE
Redo Jobs and Machines "Association"

### ISSUE THREAD

**Issue by Psyf** [CS2113-AY1819S1-T09-1/main#85]
If you don't know, there was an emergency situation right before 1.3 deadline, where we had to make tough calls and janky fixes to get 1.3 presentable for the PE.

URGENTLY fix this issue. I'm delegating @trufflepirate since he is the most qualified, and knows how to do it since he tackled the issue.

**Comment by trufflepirate** [comment]
fixed in #126
