### ISSUE TITLE
ONGOING constraints 

### ISSUE THREAD

**Issue by Psyf** [CS2113-AY1819S1-T09-1/main#90]
- RESTRICT ongoing to one print per machine
- ONGOING should be at the top of the UI

**Comment by Psyf** [comment]
Solution after talking to @teojunjie : 
- restrict `manageJob x start` to only the first Job in a machine. Two birds with one stone. 

What do you think @trufflepirate? If you agree, we have to make sure commands like `moveJob` and `bubble` can't do anything to an ONGOING job at the top. 

Is it worth implementing?

**Comment by trufflepirate** [comment]
yes. implement

**Comment by Psyf** [comment]
Okay, restrict `bubble` and `moveJob` accordingly please. 
Is there any other operation we have to restrict from ONGOINGs?

**Comment by Psyf** [comment]
Addressed in #146
